source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
	pod 'SCScrollView', '~> 1.1'
end

target 'ObjCDemo' do
	shared_pods
end

target 'Tests' do
	shared_pods
end

target 'SwiftDemo' do
	shared_pods
end